/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 17.0 		*/
/*  Created On : 16-Dec-2024 11:05:31 PM 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `交易設定` CASCADE
;

DROP TABLE IF EXISTS `訂單明細` CASCADE
;

DROP TABLE IF EXISTS `購物車` CASCADE
;

/* Create Tables */

CREATE TABLE `交易設定`
(
	`付款方式` varchar(0) NULL,
	`配送方式` varchar(0) NULL,
	`交易設定ID` varchar(0) NOT NULL,
	`訂單明細ID` varchar(0) NOT NULL,
	CONSTRAINT `PK_交易設定` PRIMARY KEY (`交易設定ID` ASC)
)

;

CREATE TABLE `訂單明細`
(
	`數量` varchar(0) NULL,
	`甜點編號` varchar(0) NULL,
	`總金額` varchar(0) NULL,
	`訂單編號` varchar(0) NULL,
	`顧客編號` varchar(0) NULL,
	`訂單明細ID` varchar(0) NOT NULL,
	`購物車ID` varchar(0) NOT NULL,
	CONSTRAINT `PK_訂單明細` PRIMARY KEY (`訂單明細ID` ASC)
)

;

CREATE TABLE `購物車`
(
	`數量` varchar(0) NULL,
	`甜點編號` varchar(0) NULL,
	`購物車ID` varchar(0) NOT NULL,
	CONSTRAINT `PK_購物車` PRIMARY KEY (`購物車ID` ASC)
)

;

/* Create Foreign Key Constraints */

ALTER TABLE `交易設定` 
 ADD CONSTRAINT `FK_交易設定_訂單明細`
	FOREIGN KEY (`訂單明細ID`) REFERENCES `訂單明細` (`訂單明細ID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `訂單明細` 
 ADD CONSTRAINT `FK_訂單明細_購物車`
	FOREIGN KEY (`購物車ID`) REFERENCES `購物車` (`購物車ID`) ON DELETE No Action ON UPDATE No Action
;

SET FOREIGN_KEY_CHECKS=1
; 
