SET FOREIGN_KEY_CHECKS=0
; 

DROP TABLE IF EXISTS TRANSACTIONSETTING CASCADE
;

DROP TABLE IF EXISTS ORDERDETAIL CASCADE
;

DROP TABLE IF EXISTS SHOPPINGCART CASCADE
;

CREATE TABLE TRANSACTIONSETTING
(
	PAYMENT varchar(0) NULL,
	DELIVERY varchar(0) NULL,
	TRANSACTIONSETTINGID varchar(0) NOT NULL,
	ORDERDETAILID varchar(0) NOT NULL,
	CONSTRAINT PK_TRANSACTIONSETTING PRIMARY KEY (TRANSACTIONSETTINGID ASC)
)

;

CREATE TABLE ORDERDETAIL
(
	QUANTITY varchar(0) NULL,
	DESSERTNUMBER varchar(0) NULL,
	AMOUNT varchar(0) NULL,
	ORDERNUMBER varchar(0) NULL,
	CUSTOMERNUMBER varchar(0) NULL,
	ORDERDETAILID varchar(0) NOT NULL,
	SHOPPINGCARTID varchar(0) NOT NULL,
	CONSTRAINT PK_ORDERDETAIL PRIMARY KEY (ORDERDETAILID ASC)
)

;

CREATE TABLE SHOPPINGCART
(
	QUANTITY varchar(0) NULL,
	DESSERTNUMBER varchar(0) NULL,
	SHOPPINGCARTID varchar(0) NOT NULL,
	CONSTRAINT PK_SHOPPINGCART PRIMARY KEY (SHOPPINGCARTID ASC)
)

;

/* Create Foreign Key Constraints */

ALTER TABLE TRANSACTIONSETTING 
 ADD CONSTRAINT FK_TRANSACTIONSETTING_ORDERDETAIL
	FOREIGN KEY (ORDERDETAILID) REFERENCES ORDERDETAIL (ORDERDETAILID) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE ORDERDETAIL 
 ADD CONSTRAINT FK_ORDERDETAIL_SHOPPINGCART
	FOREIGN KEY (SHOPPINGCARTID) REFERENCES SHOPPINGCART (SHOPPINGCARTID) ON DELETE No Action ON UPDATE No Action
;

SET FOREIGN_KEY_CHECKS=1
; 


/* --------------------------------- */


DROP TABLE IF EXISTS TRANSACTIONSETTING CASCADE;
DROP TABLE IF EXISTS ORDERDETAIL CASCADE;
DROP TABLE IF EXISTS SHOPPINGCART CASCADE;

CREATE TABLE TRANSACTIONSETTING (
    PAYMENT VARCHAR(255) NULL,
    DELIVERY VARCHAR(255) NULL,
    TRANSACTIONSETTINGID VARCHAR(255) NOT NULL,
    ORDERDETAILID VARCHAR(255) NOT NULL,
    CONSTRAINT PK_TRANSACTIONSETTING PRIMARY KEY (TRANSACTIONSETTINGID)
);

CREATE TABLE ORDERDETAIL (
    QUANTITY INTEGER NULL,
    DESSERTNUMBER INTEGER NULL,
    AMOUNT INTEGER NULL,
    ORDERNUMBER INTEGER NULL,
    CUSTOMERNUMBER INTEGER NULL,
    ORDERDETAILID VARCHAR(255) NOT NULL,
    SHOPPINGCARTID VARCHAR(255) NOT NULL,
    CONSTRAINT PK_ORDERDETAIL PRIMARY KEY (ORDERDETAILID)
);

CREATE TABLE SHOPPINGCART (
    QUANTITY INTEGER NULL,
    DESSERTNUMBER INTEGER NULL,
    SHOPPINGCARTID VARCHAR(255) NOT NULL,
    CONSTRAINT PK_SHOPPINGCART PRIMARY KEY (SHOPPINGCARTID)
);

ALTER TABLE TRANSACTIONSETTING 
ADD CONSTRAINT FK_TRANSACTIONSETTING_ORDERDETAIL
FOREIGN KEY (ORDERDETAILID) REFERENCES ORDERDETAIL (ORDERDETAILID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE ORDERDETAIL 
ADD CONSTRAINT FK_ORDERDETAIL_SHOPPINGCART
FOREIGN KEY (SHOPPINGCARTID) REFERENCES SHOPPINGCART (SHOPPINGCARTID) ON DELETE NO ACTION ON UPDATE NO ACTION;